### ISSUE TITLE
Doesn't build with GHC 7.10 and below

### ISSUE THREAD

**Issue by Lysxia** [chadaustin/buffer-builder#16]
The newly added `Semigroup` instances are currently not compatible with GHC <= 7.10.

https://matrix.hackage.haskell.org/package/buffer-builder

Would it be possible to fix the lower bounds for `buffer-builder-0.2.4.5` on Hackage so that dependency solvers can catch it?

**Comment by andyfriesen** [comment]
Sounds reasonable to me.

If you've got the time, submit a PR.  If not, we'll try our best to get to it when we have a spare moment. :)

**Comment by Lysxia** [comment]
I opened a PR for retro-compatibility, but adding a dependency might require bumping the package version (I'm not sure). So a lower bound `base >= 4.9` would be required for the currently released version, and this has to be done via Hackage in any case.

**Comment by chadaustin** [comment]
I will try to remember to push a new version soon.

**Comment by chadaustin** [comment]
OK, after the PR has landed, I've verified buffer-builder builds and passes tests on Ubuntu 16.04 (ghc 7.10).

I've also verified `stack --resolver lts-2.22 test` and `stack --resolver lts-6.35 test` pass.

Maybe it's worth setting up CI for those.

I'll upload a new version to hackage now.

**Comment by chadaustin** [comment]
It's up! https://hackage.haskell.org/package/buffer-builder

Feel free to reopen if something else goes wrong.
