### ISSUE TITLE
buffer-builder-0.2.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [chadaustin/buffer-builder#2]
It appears the header file `branchlut.h` is missing: http://hydra.cryp.to/build/577987/nixlog/2/raw?

**Comment by chadaustin** [comment]
Thanks @peti!  0.2.0.2 is uploaded and it should work now.

**Comment by peti** [comment]
Version 0.2.0.2 now fails like this:

```
Preprocessing test suite 'tests' for buffer-builder-0.2.0.2...

test/Main.hs:5:18:
    Could not find module ‘BufferTest’
    Use -v to see a list of the files searched for.

test/Main.hs:6:18:
    Could not find module ‘Utf8Test’
    Use -v to see a list of the files searched for.

test/Main.hs:7:18:
    Could not find module ‘JsonTest’
    Use -v to see a list of the files searched for.
```

**Comment by Xe** [comment]
@peti, Odd, I have been able to get the tests to pass on my local machine. I think this belongs in its own ticket though. In the new ticket can you paste in a minimal set of nix configuration that replicates the issue?

**Comment by peti** [comment]
Make sure that you run tests using the sources created by `cabal sdist`. These modules exist in your repository, I suppose, but you don't include them in the release tarball.

**Comment by andyfriesen** [comment]
This should be fixed.  Thanks!

**Comment by chadaustin** [comment]
@peti Thanks so much for the reports.

This is my first Haskell package and I suppose I assumed that if "sdist" succeeded that the package would be good to go.

**Comment by peti** [comment]
Arguably, that's how it should be! `cabal` _should_ detect that those files are missing, and it has the means to accomplish that, too. It's just that nobody implemented that particular feature yet.
